void cloneReset(void);
void comboRandomizer1(void);
void comboRandomizer2(void);
void partGetter1(void);
void partGetter2(void);
void partsCheck1(void);
void partsCheck2(void);
void userChoiceAlign1(struct User user_choice);
void userChoiceAlign2(struct User user_choice);
void userSelect1(void);
void userSelect2(void);
int comboRandomizerWhileLoop(int z);
int playerCount(void);
int simpleRatchetIfNeedBe(void);
int avbitcnt;
int avbladecnt;
int avmainbladecnt;
int avratchetcnt;
int acsimplerathcetcnt;
int bittest=0;
int bladetest=0;
int choiceAssistBlade;
int choiceBit;
int choiceBlade;
int choiceLockChip;
int choiceMainBlade;
int choiceRatchet;
int choiceRatchetIntegratedBit;
int contgen;
int deckSize=0;
int finalDeckSize;
int nocxtest=0;
int nononcxtest=0;
int nomlc;
int numOfDeck;
int playercnt;
int ratchettest=0;
int simpleratchettest;
int skipgentest;
int userChoice;
char nextDeck;
char decision;
char userDecision;
const char* str1;
const char* str2;
const char* str3;