int user_Snek_Blades_bladecnt=39; int user_Snek_Blades_assistbladecnt=7; int user_Snek_Blades_ratchetcnt=21; int user_Snek_Blades_lockchipcnt=7; int user_Snek_Blades_bitcnt=32;
char user_blade_Snek_Blades[1000][50]={"Cobalt Dragoon", "Crimson Garuda", "Dran Dagger", "Dran Sword", "Knight Shield", "Leon Claw", "Phoenix Wing", "Samurai Calibur", "Shark Edge", "Sphinx Cowl", "Tyranno Beat", "Unicorn Sting", "Weiss Tiger", "Whale Wave", "Wizard Arrow", "Wyvern Gale", "Dran Buster", "Hells Hammer", "Impact Drake", "Leon Crest", "Samurai Saber", "Shinobi Shadow", "Silver Wolf", "Wizard Rod",  "Lightning L-Drago" "Bite Croc", "Gill Shark", "Knife Shinobi", "Savvage Bear", "Steel Samurai", "Talon Ptera", "Tusk Mammoth", "Arc", "Blast", "Brave", "Brush", "Dark", "Flame", "Reaper"};
char user_assist_blade_Snek_Blades[100][50]={"A", "B", "J", "R", "S", "T", "W"};
char user_ratchet_Snek_Blades[100][50]={"Tr", "0-80", "1-60", "1-80", "2-60", "2-70", "3-60", "3-70", "3-80", "4-55", "4-60", "4-70", "4-80", "5-60", "5-70", "5-80", "6-60", "6-70", "6-80", "7-60", "9-60"};
char user_bit_Snek_Blades[100][50]={"A", "B", "C", "DB", "E", "F", "FB", "GB", "GF", "GN", "GP", "H", "HN", "K", "L", "LF", "LO", "LR", "M", "MN", "N", "O", "P", "Q", "R", "S", "T", "TP", "U", "V", "W", "WB"};
char user_lock_chip_Snek_Blades[100][50]={"Cerberus", "Dran", "Fox", "Hells", "Pegasus", "Perseus", "Wizard"};
int user_bx_bladecnt=72; int user_bx_assistbladecnt=0; int user_bx_ratchetcnt=15; int user_bx_lockchipcnt=0; int user_bx_bitcnt=22;
char user_blade_bx[1000][50]={"Black Shell", "Cobalt Dragoon", "Cobalt Drake", "Crimson Garuda", "Dran Dagger", "Dran Sword", "Hells Chain", "Hells Scythe", "Knight Lance", "Knight Shield", "Leon Claw", "Pheonix Feather", "Phoenix Wing", "Rhino Horn", "Samurai Calibur", "Shark Edge", "Shelter Drake", "Sphinx Cowl", "Tricera Press", "Tyranno Beat", "Unicorn Sting", "Viper Tail", "Weiss Tiger", "Whale Wave", "Wizard Arrow", "Wyvern Gale", "Bite Croc", "Gill Shark", "Knife Shinobi", "Ridge Triceratops", "Roar Tyranno", "Savage Bear", "Samurai Steel", "Tackle Goat", "Talon Ptera", "Tuck Mammoth", "Yell Kong", "Dragoon Storm", "Dranzer Spiral", "Driger Slash", "Draciel Shield", "Lightning L-Drago", "Rock Leone", "Storn Pegasus", "Victory Valkyrie", "Xeno Xcalibur", "Mosasaurus", "Quetzalcoatlus", "Spinosaurus", "T-Rex", "Captain America", "Green GOblin", "Iron Man", "Miles Morales", "Red Hulk", "Spder-Man", "Thanos", "Venom", "Chewbacca", "Darth Vader", "General Grievous", "Luke Skywalker", "Moff Gideon", "Obi-Wan Kenobi", "Stormtrooper", "The Mandalorian", "Bumblebee", "Megatron", "Optimus Primal", "Optimus Prime", "Shockwave", "Starscream"};
char user_ratchet_bx[100][50]={"1-70", "2-60", "2-80", "3-60", "3-80", "4-60", "4-70", "4-80", "5-60", "5-80", "6-70", "7-70", "9-60", "9-80", "M-85"};
char user_bit_bx[100][50]={"B", "C", "D", "E","F", "GB", "GF", "GN", "GP", "HN", "HT", "LF", "M", "N", "O", "P", "Q", "R", "S", "T", "TP", "U"};
char user_assist_blade_bx[100][50];
char user_lock_chip_bx[100][50];
int user_ux_bladecnt=21; int user_ux_assistbladecnt=0; int user_ux_ratchetcnt=14; int user_ux_lockchipcnt=0; int user_ux_bitcnt=14;
char user_lock_chip_ux[100][50];
char user_assist_blade_ux[100][50];
char user_blade_ux[1000][50]={"Aero Pegasus", "Clock Mirage", "Dran Buster", "Ghost Circle", "Golem Rock", "Hells Hammer", "Impact Drake", "Kight Mail", "Leon Crest", "Meteor Dragoon", "Mummy Curse", "Orochi Cluster", "Pheonix Rudder", "Samurai Saber", "Scorpio Spear", "Shark Scale", "Shinobi Shadow", "Silver Wolf", "Wizard Rod", "Hover Wyvern", "Stun Medusa"};
char user_ratchet_ux[100][50]={"0-70", "0-80", "2-70", "3-70", "3-85", "7-60", "7-70", "7-75", "1-60", "1-80", "9-65", "9-70", "4-50", "5-70"};
char user_bit_ux[100][50]={"A", "BS", "DB", "FB", "G", "H", "J", "L", "LR", "MN", "RA", "UF", "UN", "Z"};
int user_cx_bladecnt=16; int user_cx_assistbladecnt=13; int user_cx_ratchetcnt=6; int user_cx_lockchipcnt=17; int user_cx_bitcnt=8;
char user_lock_chip_cx[100][50]={"Cerberus", "Dran", "Fox", "Hells", "Hornet", "Kraken", "Leon", "Emperor", "Pegasus", "Perseus", "Phoenix", "Sol", "Stag", "Valkyrie", "Whale", "Wolf", "Wizard"};
char user_blade_cx[1000][50]={"Antler", "Arc", "Blast", "Brave", "Brush", "Dark", "Eclipse", "Fang", "Flame", "Flare", "Fort", "Hunt", "Might", "Reaper", "Volt", "Wriggle"};
char user_assist_blade_cx[100][50]={"A", "B", "C", "D", "F", "H", "J", "M", "R", "S", "T", "W", "Z"};
char user_ratchet_cx[100][50]={"0-60", "4-55", "6-60", "6-80", "Op", "Tr"};
char user_bit_cx[100][50]={"GR", "K", "LO", "TK", "V", "WB", "WW", "W"};
int user_Yako_bladecnt=12; int user_Yako_assistbladecnt=1; int user_Yako_lockchipcnt=1; int user_Yako_ratchetcnt=11; int user_Yako_bitcnt=12;
char user_blade_Yako[1000][50]={"Whale Wave", "Leon Claw", "Gill Shark", "Phoenix Wing", "Arc", "Shark Edge", "Clock Mirage", "Wizard Arrow", "Sphinx Cowl", "Viper Tail", "Leon Crest", "Golem Rock"};
char user_assist_blade_Yako[100][50]={"R"};
char user_lock_chip_Yako[100][50]={"Wizard"};
char user_ratchet_Yako[100][50]={"5-80", "5-60", "9-65", "4-55", "9-60", "3-60", "4-80", "1-80", "5-70", "1-60", "7-60"};
char user_bit_Yako[100][50]={"GF", "UN", "F", "D", "H", "GN", "GB", "O", "T", "HN", "B", "Q"};